# List the pdf's to build. foo.tex will produce foo.pdf
TARGETS = humangl.pdf

# List the files included in the slides
DEPS = humangl-walking.png

# Relative path to the LaTeX documentclass setup files
# Adapt as needed
RELPATH = ../latex/

# You should not touch this either
include $(RELPATH)/Makefile.LaTeX
